module.exports={
    databaseUserName:process.env.DATABASE_USER_NAME,
    databaseName:process.env.DATABASE_NAME,
    databasePassword:process.env.DATABASE_PASSWORD,
    apiLoginKey:process.env.API_LOGIN_KEY,
    transactionKey:process.env.TRACNSACTION_KEY,
    key:process.env.KEY,
    jwtKey:process.env.JWT_KEY
}